# **Data Engineering Fundamentals Project**

## **Objective:**

Convert a dataset between text and binary formats and analyze the differences.

## **1. Data Format Conversion**

### **Create a dataset in CSV format**

In [1]:
# Import libraries

import pandas as pd
import random

In [ ]:
# Craete the lists

names = [
    "Amina", "Kevin", "Sofia", "Patrick", "Nadia",
    "Samuel", "Chloe", "Eric", "Maya", "Lucas"]

cities = [
    "Ottawa", "Toronto", "Montreal", "Vancouver", "Calgary",
    "Edmonton", "Winnipeg", "Halifax", "Quebec City", "Victoria"]

In [ ]:
# Generate 100 users

fictional_user_data = []

for i in range(100):
    name = random.choice(names)
    age = random.randint(18, 70)
    city = random.choice(cities)
    
    fictional_user_data.append([name, age, city])

In [ ]:
# Create a dataframe

fictional_user_df = pd.DataFrame(fictional_user_data, columns=["Name", "Age", "City"])

fictional_user_df.head()

      Name  Age       City
0    Nadia   36  Vancouver
1     Eric   58    Calgary
2    Kevin   25   Victoria
3  Patrick   55    Halifax
4  Patrick   37     Ottawa

In [5]:
# Save the dataset as csv format

fictional_user_df.to_csv("fictional_user_df.csv", index=False)

### **Convert the CSV file to Parquet format**

In [8]:
fictional_user_df.to_parquet("fictional_user_df.parquet", index=False)

### **Load the parquet file back**

In [9]:
df_parquet = pd.read_parquet("fictional_user_df.parquet")

df_parquet.head()

      Name  Age       City
0    Nadia   36  Vancouver
1     Eric   58    Calgary
2    Kevin   25   Victoria
3  Patrick   55    Halifax
4  Patrick   37     Ottawa

## **2. Implementing ETL Process**